require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :rows, :ids, :noko
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:ne/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
		  line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 

	def fetch_page
		page = RestClient.get("http://www.sos.ne.gov/elec/clerks.html")
		@noko = Nokogiri::HTML(page).css('#contentPadding')
	end

	def iterate_through_page
		i = 1
		while i < 94 do # Goes up to York
			jurisdiction_name = noko.css('div')[i].first_element_child.attribute('name').value.capitalize + " County"
			office = jurisdiction_name + " Clerk"
			phone = noko.css('div')[i].text.scan(/\(\d{3}\)\s\d{3}-\d{4}/).first
			#website = noko.css('.mdgov_contentWrapper').css('p')[i].elements.select { |el| el.attribute('href') }.first.text
			id = @ids.find do |i| #for cities I have to search
				name = jurisdiction_name.rstrip.gsub(" County", "").gsub(" ", "_").gsub("'","~").gsub(".","")
				i =~ /county:#{name}/i
			end || ""
			i += 1
			@rows << [jurisdiction_name, "Nebraska", office, phone, id]	
		end


	end			

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.fetch_page
a.iterate_through_page
a.write_into_CSV_file
