require 'mechanize'
require "rest_client"
require 'pry-nav'
require 'nokogiri'
require 'csv'

class Scraper 
	attr_reader :rows, :ids, :noko
	def initialize
		@rows = []
	end

	def get_ocd_ids
		page = RestClient.get("https://raw.githubusercontent.com/opencivicdata/ocd-division-ids/master/identifiers/country-us/census_autogenerated/us_census_places.csv")
		noko = Nokogiri::HTML(page)
		@ids = noko.text.lines.select do |line|
			line =~ /state:nj/
		end.reject do |line|
			line =~ /place:/
		end.map do |line|
		  line.gsub(/,.+/, '').gsub(/\n/, '')
		end 
	end 

	def fetch_page
		page = RestClient.get("http://www.state.nj.us/state/elections/voting-information-local-officials.html")
		@noko = Nokogiri::HTML(page)
	end

	def iterate_through_page
		i = 0
		while i < 21 do # Goes up to Warren, NJ
			jurisdiction_name = noko.css('.table_head_grey')[i].text + " County"
			office = jurisdiction_name + " Board of Elections"
			phone = noko.css('#table_row_last')[i+1].css('.table_column_2')[2].text.scan(/\d{3}\-\d{3}-\d{4}/).first

			website = noko.css('#table_row_last')[i+1].css('.table_column_2')[2].css('a').attribute('href').value
			id = @ids.find do |i| #for cities I have to search
				name = jurisdiction_name.rstrip.gsub(" County", "").gsub(" ", "_").gsub("'","~").gsub(".","")
				i =~ /county:#{name}/i
			end || ""
			i += 1
			@rows << [jurisdiction_name, "New Jersey", office, phone, website, id]	
		end


	end			

	def write_into_CSV_file
		CSV.open("spreadsheet.csv", "wb") do |csv|
			@rows.map do |line|
				csv << line
			end
		end
	end

end

a = Scraper.new
a.get_ocd_ids
a.fetch_page
a.iterate_through_page
a.write_into_CSV_file